spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shg_database
    username: root
    password: password

server:
  port: 9999

security:
  jwt:
    expiration: 432000
    secret: secret_of_shg

mybatis:
  mapper-locations: classpath*:/mybatis/*.xml